### PR TITLE
composer: allow PHP 8, so Rector can use it fully

### PR DESCRIPTION
**Pull request by TomasVotruba**
Hi, 
I'm trying to composer install Rector book, but fail with PHP 8 here.

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Sure thing, do you know how to run the tests with PHP 8.0 as well?

**Comment by matthiasnoback** [comment]
I mean using GitHub actions.

**Comment by matthiasnoback** [comment]
I'll look into it myself, seems like it's a very easy thing to do :)

**Comment by TomasVotruba** [comment]
If it's trouble let me know. I've been using them for a year and love to migrate them :)

**Pull request merged**
